### ISSUE TITLE
All buttons in the settings are invalid, including the back button

### ISSUE THREAD

**Issue by Maker-Elias** [EvanEMV/Baba-Is-You---Metatext-Mod#3]
**![image](https://user-images.githubusercontent.com/118045451/218142405-02532b9c-b2a6-4fcc-933c-f043a9770cb6.png)**
**By the way, I put the Lua and Sprites folders under the Level Pack.**

**Comment by EmilyEmmi** [comment]
I believe this was caused by a recent update to how the button_clicked hook works. I will try to fix it as soon as I can.

**Comment by EmilyEmmi** [comment]
This issue is now resolved. Thank you for reporting this!
